- .github/workflows/pytest.yaml
- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/actions/clear.py
- meerschaum/config/_version.py
- meerschaum/connectors/__init__.py
- meerschaum/connectors/sql/_fetch.py
- meerschaum/connectors/sql/_pipes.py
- meerschaum/core/Pipe/__init__.py
- meerschaum/core/Pipe/_attributes.py
- meerschaum/core/Pipe/_fetch.py
- meerschaum/core/Pipe/_sync.py
- meerschaum/utils/misc.py
- meerschaum/utils/packages/__init__.py
- meerschaum/utils/packages/_packages.py
- meerschaum/utils/pool.py
- meerschaum/utils/venv/__init__.py
- setup.py
- **Added the `@make_connector` decorator.**  
Plugins may now extend the base `Connector` class to provide custom connectors. For most cases, the built-in `plugin` connector should work fine. This addition opens up the internal connector system so that plugin authors may now add new types. See below for a minimal example of a new connector class:
```python
from meerschaum.connectors import make_connector, Connector
REQUIRED_ATTRIBUTES = {'username', 'password'}
@make_connector
class FooConnector(Connector):
def __init__(self, label: str, **kw):
"""
Instantiate the base class and verify the required attributes are present.
"""
kw['label'] = label
super().__init__('foo', **kw)
self.verify_attributes(REQUIRED_ATTRIBUTES)
def fetch(self, pipe, **kw):
"""
Return a dataframe (or list of dicts …
```
> 🔖 v1.2.1 Added `@make_connector` and allow for omitting datetime columns.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/__main__.py
- meerschaum/actions/sync.py
- meerschaum/config/_version.py
- meerschaum/connectors/sql/_pipes.py
- meerschaum/core/Pipe/_register.py
- meerschaum/core/Pipe/_sync.py
- meerschaum/utils/formatting/__init__.py
- meerschaum/utils/misc.py
- **Custom connectors may now have `register(pipe)` methods.**  
Just like the module-level `register(pipe)` plugin function, custom connectors may also provide this function as a class member.
- **Print a traceback if `fetch(pipe)` breaks.**  
A more verbose traceback is printed if a plugin breaks during the syncing process.
- **Cleaned up `sync pipes` output.**  
This patch cleans up the syncing process's pretty output.
- **Respect `--nopretty` in `sync pipes`.**  
This flag will only print JSON-encoded dictionaries for `sync pipes`. Tracebacks may still interfere without standard output, however.
> 🔖 v1.2.8 More verbose tracebacks, added `register()` for custom connectors, and more.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/api/dash/pipes.py
- meerschaum/config/_default.py
- meerschaum/config/_version.py
- meerschaum/connectors/api/_pipes.py
- meerschaum/connectors/parse.py
- meerschaum/connectors/sql/SQLConnector.py
- meerschaum/connectors/sql/_pipes.py
- meerschaum/connectors/sql/_sql.py
- meerschaum/core/Pipe/__init__.py
- meerschaum/core/Pipe/_attributes.py
- meerschaum/core/Pipe/_dtypes.py
- meerschaum/core/Pipe/_sync.py
- meerschaum/utils/misc.py
- meerschaum/utils/sql.py
- meerschaum/utils/venv/__init__.py
- tests/connectors.py
- tests/test_pipes.py
**Improvements**
- **Syncing now handles dynamic columns.**  
Syncing a pipe with new columns will trigger an `ALTER TABLE` query to append the columns to your table:
```python
pipe = mrsm.Pipe('foo', 'bar', instance='sql:memory')
pipe.sync([{'a': 1}])
print(pipe.get_data())
pipe.sync([{'b': 1}])
print(pipe.get_data())
```
If you've specified index columns, you can use this feature to fill in `NULL` values in your table:
```python
'foo', 'bar',
columns = {'id': 'id_col'},
instance = 'sql:memory',
)
pipe.sync([{'id_col': 1, 'a': 10.0}])
pipe.sync([{'id_col': 1, 'b': 20.0}])
print(pipe.get_data())
```
- **Add as many indices as you like.**  
In addition to the special index column labels `datetime`, `id`, and `value`, the …
> v1.3.0: Dynamic Columns

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/config/_version.py
- meerschaum/connectors/sql/_pipes.py
- meerschaum/connectors/sql/_sql.py
- meerschaum/core/Pipe/__init__.py
- meerschaum/core/Pipe/_attributes.py
- meerschaum/core/Pipe/_delete.py
- meerschaum/core/Pipe/_dtypes.py
- meerschaum/core/Pipe/_edit.py
- meerschaum/core/Pipe/_sync.py
- meerschaum/utils/misc.py
- meerschaum/utils/sql.py
- scripts/test.sh
- tests/test_pipes.py
- **Fixed data type enforcement issues.**  
A serious bug in data type enforcement has been patched.
- **Allow `Pipe.dtypes` to be edited.**  
You can now set keys in `Pipe.dtypes` and persist them with `Pipe.edit()`.
- **Added `Pipe.update()`.**  
`Pipe.update()` is an alias to `Pipe.edit(interactive=False)`.
- **`Pipe.delete()` no longer deletes local attributes.**  
It still removes `Pipe.id`, but local attributes will now remain intact.
- **Fixed dynamic columns on DuckDB.**  
DuckDB does not allow for altering tables when indices are created, so this patch will drop and rebuild indices when tables are altered.
- **Replaced `CLOB` with `NVARCHAR(2000)` on Oracle SQL.**  
This may require migrating existing pipes to use the new data type.
- **Enforce integers are of type `INTEGER` on …
> 🐛 v1.3.1 Fix dtype enforcement issues.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/_internal/entry.py
- meerschaum/_internal/shell/Shell.py
- meerschaum/actions/register.py
- meerschaum/actions/show.py
- meerschaum/actions/stack.py
- meerschaum/actions/sync.py
- meerschaum/config/_version.py
- meerschaum/connectors/plugin/PluginConnector.py
- meerschaum/connectors/poll.py
- meerschaum/core/Pipe/_fetch.py
- meerschaum/core/Pipe/_register.py
- meerschaum/core/Pipe/_sync.py
- meerschaum/utils/formatting/_pipes.py
- meerschaum/utils/get_pipes.py
- meerschaum/utils/packages/__init__.py
- meerschaum/utils/sql.py
- meerschaum/utils/threading.py
- meerschaum/utils/venv/_Venv.py
- meerschaum/utils/venv/__init__.py
- **Fixed virtual environment issues when syncing.**  
This one's a doozy. Before this patch, there would frequently be warnings and sometimes exceptions thrown when syncing a lot of pipes with a lot of threads. This kind of race condition can be hard to pin down, so this patch reworks the virtual environment resolution system by keeping track of which threads have activated the environments and refusing to deactivate if other threads still depend on the environment. To enforce this behavior, most manual ivocations of [`activate_venv()`](https://docs.meerschaum.io/utils/venv/index.html#meerschaum.utils.venv.activate_venv) were replaced with the [`Venv` context manager](https://docs.meerschaum.io/utils/venv/index.html#meerschaum.utils.venv.Venv). Finally, the last stage of each action is …
> 🧵 v1.3.10 Improved virtual environment resolution with multithreading.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/actions/api.py
- meerschaum/api/__init__.py
- meerschaum/api/dash/pipes.py
- meerschaum/config/_default.py
- meerschaum/config/_version.py
- meerschaum/connectors/sql/SQLConnector.py
- meerschaum/connectors/sql/_create_engine.py
- meerschaum/connectors/sql/_fetch.py
- meerschaum/connectors/sql/_pipes.py
- meerschaum/core/Pipe/_dtypes.py
- meerschaum/core/Pipe/_sync.py
- meerschaum/utils/sql.py
- tests/pipes.py
- tests/test_pipes.py
- **Added in-place syncing for SQL pipes.**  
This feature is big (enough to warrant a new point release). When pipes with the same instance connector and data source connector are synced, the method `sync_pipe_inplace()` is invoked. For SQL pipes, this means the entire syncing process will now happen entirely in SQL, which can lead to massive performance improvements.
```python
conn = mrsm.get_connector('sql', 'local')
conn.to_sql(pd.DataFrame([{'a': 1}]), 'foo')
"sql:local", "foo",
instance = "sql:local",
parameters = {
"query": "SELECT * FROM foo"
},
)
pipe.sync()
```
To disable this behavior, run the command `edit config system` and set the value under the keys `experimental:inplace_sync` to `false`.
- **Added negation to …
> ✨ v1.4.0 In-place syncing, `--params` improvements, and more.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/actions/api.py
- meerschaum/api/__init__.py
- meerschaum/api/dash/pipes.py
- meerschaum/config/_default.py
- meerschaum/config/_version.py
- meerschaum/connectors/sql/SQLConnector.py
- meerschaum/connectors/sql/_create_engine.py
- meerschaum/connectors/sql/_fetch.py
- meerschaum/connectors/sql/_pipes.py
- meerschaum/core/Pipe/_dtypes.py
- meerschaum/core/Pipe/_sync.py
- meerschaum/utils/sql.py
- tests/pipes.py
- tests/test_pipes.py
- **Added in-place syncing for SQL pipes.**  
This feature is big (enough to warrant a new point release). When pipes with the same instance connector and data source connector are synced, the method `sync_pipe_inplace()` is invoked. For SQL pipes, this means the entire syncing process will now happen entirely in SQL, which can lead to massive performance improvements.
```python
conn = mrsm.get_connector('sql', 'local')
conn.to_sql(pd.DataFrame([{'a': 1}]), 'foo')
"sql:local", "foo",
instance = "sql:local",
parameters = {
"query": "SELECT * FROM foo"
},
)
pipe.sync()
```
To disable this behavior, run the command `edit config system` and set the value under the keys `experimental:inplace_sync` to `false`.
- **Added negation to …
> v1.4.1 Inplace syncing, `--params` improvements, and more

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/config/_version.py
- meerschaum/connectors/sql/_pipes.py
- meerschaum/utils/sql.py
- **Bugfixes and stability improvements.**  
These versions included several bugfixes, such as patching `--skip-check-existing` for in-place syncs and fixing the behavior of `--params` ([`build_where()`](https://docs.meerschaum.io/utils/sql.html#meerschaum.utils.sql.build_where)).
> 🐛 v1.4.7 Bugfixes and stability improvements.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/actions/api.py
- meerschaum/config/__init__.py
- meerschaum/config/_version.py
- meerschaum/connectors/__init__.py
- meerschaum/connectors/sql/_pipes.py
- meerschaum/connectors/sql/_users.py
- meerschaum/connectors/sql/tables/__init__.py
- meerschaum/core/Pipe/_attributes.py
- meerschaum/core/Pipe/_bootstrap.py
- meerschaum/core/Pipe/_clear.py
- meerschaum/core/Pipe/_data.py
- meerschaum/core/Pipe/_delete.py
- meerschaum/core/Pipe/_drop.py
- meerschaum/core/Pipe/_edit.py
- meerschaum/core/Pipe/_register.py
- meerschaum/core/Pipe/_sync.py
- meerschaum/plugins/__init__.py
- meerschaum/utils/packages/_packages.py
- meerschaum/utils/sql.py
- meerschaum/utils/venv/__init__.py
- requirements/api.txt
- requirements/full.txt
- scripts/portable/build.sh
- **Fixed in-place syncs for aggregate queries.**  
In-place SQL syncs which use aggregation functions are now handled correctly. This version addresses differences in column types between backtrack and new data. For example, the following query will now be correctly synced:
```sql
WITH days_src AS (
SELECT *, DATE_TRUNC('day', "datetime") AS days
FROM plugin_stress_test
)
SELECT days, AVG(val) AS avg_value
FROM days_src
GROUP BY days
```
- **Activate virtual environments for custom instance connectors.**  
All pipe methods now activate virtual environments for custom instance connectors.
- **Improved database connection performance.**  
Cold connections to a SQL database have been sped up by replacing `sqlalchemy_utils` with handwritten logic (JSON for PostgreSQL-like and SQLite).
- …
> ⚡️ v1.4.9 Performance boost, bugfixes, and more.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/__init__.py
- meerschaum/config/_version.py
- meerschaum/connectors/__init__.py
- meerschaum/connectors/api/_login.py
- meerschaum/connectors/sql/_pipes.py
- meerschaum/core/Pipe/_register.py
- meerschaum/core/Pipe/_sync.py
- meerschaum/plugins/_Plugin.py
- meerschaum/utils/misc.py
- meerschaum/utils/venv/__init__.py
- meerschaum/utils/warnings.py
- **Fixed an issue with syncing background jobs.**  
The `--name` flag of background jobs with colliding with the `name` keyword argument of `SQLConnector.to_sql()`.
- **Fixed a datetime bounding issue when `datetime` index is omitted.**  
If the minimum datetime value of the incoming dataframe cannot be determined, do not bound the `get_data()` request.
- **Keep existing parameters when registering plugin pipes.**  
When a pipe is registered with a plugin as its connector, the return value of the `register()` function will be patched with the existing in-memory parameters.
- **Fixed a data type syncing issue.**  
In cases where fetched data types do not match the data types in the pipe's table (e.g. automatic datetime columns), a bug has been patched to ensure the correct data types are …
> 🐛 v1.4.10 Fixed edge case bugs in syncing, data type enforcement, and more.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/actions/start.py
- meerschaum/config/_version.py
- meerschaum/connectors/sql/_fetch.py
- meerschaum/core/Pipe/_bootstrap.py
- meerschaum/core/Pipe/_sync.py
- meerschaum/utils/venv/__init__.py
- **Fixed an issue when syncing empty DataFrames [(#95)](https://github.com/bmeares/Meerschaum/issues/95).**  
When syncing an empty list of documents, `Pipe.filter_existing()` would trigger pulling the entire table into memory. This patch adds a check if the dataframe is empty.
- **Allow the `datetime` column to be omitted in the `bootstrap` wizard.**  
Now that the `datetime` index is optional, the bootstrapping wizard allows users to skip this index.
- **Fixed a small issue when syncing to MySQL.**  
Due to the addition of MySQL 5.7 support in v1.4.11, a slight edge case arose which broke SQL definitions. This patch fixes MySQL behavior when a `WHERE` clause is present in the definition.
> 🐛 v1.4.13 Fixed performance issue (#95) and syncing from MySQL.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/_internal/arguments/_parser.py
- meerschaum/actions/copy.py
- meerschaum/api/__init__.py
- meerschaum/api/routes/_pipes.py
- meerschaum/config/_version.py
- meerschaum/connectors/api/_delete.py
- meerschaum/connectors/api/_get.py
- meerschaum/connectors/api/_patch.py
- meerschaum/connectors/api/_post.py
- meerschaum/connectors/sql/_pipes.py
- meerschaum/core/Pipe/__init__.py
- meerschaum/core/Pipe/_attributes.py
- meerschaum/core/Pipe/_bootstrap.py
- meerschaum/core/Pipe/_delete.py
- meerschaum/core/Pipe/_edit.py
- meerschaum/core/Pipe/_register.py
- meerschaum/core/Pipe/_sync.py
- meerschaum/utils/get_pipes.py
- meerschaum/utils/sql.py
- tests/test_pipes.py
- **Added flag `temporary` to `Pipe` (and `--temporary`).**  
Pipes built with `temporary=True`, will not create instance tables (`pipes`, `users`, and `plugins`) or be able to modify registration. This is particularly useful when creating pipes from existing tables when automatic registration is not desired.
```python
conn = mrsm.get_connector('sql:temp', uri='postgresql://user:pass@localhost:5432/db')
table_name = 'my_table'
conn.to_sql(
pd.DataFrame([{'id_column': 1, 'value': 1.0}]),
name = table_name,
)
'foo', 'bar',
target = table_name,
temporary = True,
instance = conn,
columns = {
'id': 'id_column',
},
)
docs = [
{
"id_column": 1,
"value": 123.456,
"new_column": "hello, world!",
},
]
pipe.sync(docs)
```
- **Fixed …
> 🔒️ Security patch and add `temporary` to avoid automatic table creation.

- meerschaum/actions/edit.py
- meerschaum/actions/register.py
- meerschaum/config/_patch.py
- meerschaum/config/_version.py
- meerschaum/connectors/sql/_sql.py
- **Added `--params` to `edit pipes` and `register pipes`.**  
When registering or editing a pipe, the `--params` dictionary, if provided, will be patched into the pipe's `parameters`. This should prove useful for scripting when paired with the `-y`, `-f`, or `--nopretty` flags.
- **Enforce chunksize limit with SQLite.**  
The limit was previously only enforced when reading documents. This patch extends that to `SQLConnector.to_sql()`.
> ✨ Added `--params` to `edit pipes` and `register pipes`, and enforce chunksize limit in `SQLConnector.to_sql()`.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- docs/mkdocs/reference/compose.md
- docs/mkdocs/reference/environment.md
- meerschaum/actions/stop.py
- meerschaum/config/_version.py
- meerschaum/connectors/sql/SQLConnector.py
- meerschaum/connectors/sql/_pipes.py
- meerschaum/connectors/sql/_sql.py
- meerschaum/core/Pipe/_attributes.py
- meerschaum/core/Pipe/_dtypes.py
- meerschaum/core/Pipe/_register.py
- meerschaum/core/Pipe/_sync.py
- meerschaum/plugins/_Plugin.py
- meerschaum/utils/misc.py
- meerschaum/utils/sql.py
- meerschaum/utils/typing.py
- tests/test_pipes.py
- **Pipes now support syncing dictionaries and lists.**  
Complex columns (dicts or lists) will now be preserved:
```python
pipe = mrsm.Pipe('a', 'b')
pipe.sync([{'a': {'b': 1}}])
df = pipe.get_data()
print(df['a'][0])
```
You can also force strings to be parsed by setting the data type to `json`:
```python
'foo', 'bar',
columns = {'datetime': 'id'},
dtypes = {'data': 'json', 'id': 'Int64'},
)
docs = [{'id': 1, 'data': '{"foo": "bar"}'}]
pipe.sync(docs)
df = pipe.get_data()
print(df['data'][0])
```
For PostgreSQL-like databases (e.g. TimescaleDB), this is stored as `JSONB` under the hood. For all others, it's stored as the equivalent for `TEXT`.
- **Fixed determining the version when installing plugins.**  
Like the …
> ✨ v1.5.3 Add support for syncing dictionaries and lists (`dtype=json`).

- meerschaum/config/_version.py
- meerschaum/utils/packages/_packages.py
- requirements/api.txt
- requirements/full.txt
v2.0.0 of SQLAlchemy was released today with some breaking changes. This patch holds SQLAlchemy back to <2.0.0 until compatibility has been verified.
> ⬇️ v1.5.6 Hold back `SQLAlchemy` to <2.0.0.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/config/_version.py
- meerschaum/core/Pipe/_sync.py
- meerschaum/utils/packages/__init__.py
- meerschaum/utils/sql.py
- **Replace `ast.literal_eval()` with `json.loads()` when filtering JSON columns.**  
This patch replaces the use of `str` and `ast.literal_eval()` with `json.dumps()` and `json.loads()` to preserve accuracy.
- **Fix a subtle bug with subprocesses.**  
The function `run_python_package()` now better handles environment passing and raises a more verbose warning when something goes wrong.
- **Allow columns with `'create'` in the name.**  
A security measure previously disallowed certain keywords when sanitizing input. Now columns are allowed to contain certain keywords.
> 🩹 v1.5.7 Fix minor issues when syncing large integers in a JSON column.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- docs/mkdocs/reference/data-analysis-tools.md
- docs/mkdocs/reference/plugins/writing-plugins.md
- meerschaum/config/_version.py
- meerschaum/connectors/sql/_pipes.py
- meerschaum/core/Pipe/_sync.py
- meerschaum/utils/misc.py
- meerschaum/utils/sql.py
- **Infer JSON columns from the first first non-null value.**  
When determining complex columns (dictionaries or lists), the first non-null value of the dataframe is checked rather than the first row only. This accounts for documents which contain variable keys in the same sync, e.g.:
```python
pipe = mrsm.Pipe('a', 'b')
pipe.sync([
{'a': {'b': 1}},
{'c': {'d': 2}},
])
```
- **Fix a bug when reconstructing JSON columns.**  
When rebuilding JSON values after merging, a check is first performed if the value is in fact a string (sometimes `NULLS` slip in).
> 🐛 v1.5.8 Determine JSON columns from first non-null values.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/config/_default.py
- meerschaum/config/_version.py
- meerschaum/connectors/sql/_fetch.py
- meerschaum/connectors/sql/_pipes.py
- meerschaum/connectors/sql/_sql.py
- meerschaum/core/Pipe/_sync.py
- meerschaum/utils/misc.py
- meerschaum/utils/typing.py
- tests/test_pipes.py
- **Allow pipes to sync DataFrame generators.**  
If `pipe.sync()` receives a generator (for `DataFrames`, dicctionaries, or lists), it will attempt to consume it and sync its chunks in parallel threads (this can be single-threaded with `--workers 1`). For SQL pipes, this will be capped at your configured pool size (default 5) minus the running number of threads.
This means you may now return generators to large transcations, such as reading a large CSV: 
```python
def fetch(pipe, **kw) -> Iterable['pd.DataFrame']:
return pd.read_csv('data.csv', chunksize=1000)
```
Any iterator of DataFrame-like chunks will work:
```python
def fetch(pipe, **kw) -> Generator[List[Dict[str, Any]]]:
return (
[
{'id': 1, 'val': 10.0 * i},
{'id': 2, 'val': 20.0 * i},
] for i in range(10)
)
```
This new …
> ⚡️ v1.6.5 Sync data generators (in parallel!) and fix an edge case.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/config/_version.py
- meerschaum/connectors/sql/_pipes.py
- meerschaum/utils/sql.py
- tests/test_pipes.py
- **Issue one `ALTER TABLE` query per column for SQLite.**  
SQLite does not support multiple columns in an `ALTER TABLE` query. This patch addresses this behavior and adds a specific test for this scenario.
> v1.6.6 SQLite fix

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/_internal/arguments/_parser.py
- meerschaum/config/_version.py
- meerschaum/connectors/sql/_fetch.py
- meerschaum/connectors/sql/_sql.py
- meerschaum/core/Pipe/__init__.py
- meerschaum/core/Pipe/_data.py
- meerschaum/core/Pipe/_fetch.py
- meerschaum/core/Pipe/_sync.py
- meerschaum/utils/sql.py
- tests/test_pipes.py
- **Added `as_iterator` to `Pipe.get_data()`.**  
Passing `as_iterator=True` (or `as_chunks`) to `Pipe.get_data()` returns a generator which returns chunks of Pandas DataFrames.
Each DataFrame is the result of a `Pipe.get_data()` call with intermediate datetime bounds between `begin` and `end` of size `chunk_interval` (default `datetime.timedelta(days=1)` for time-series / 100,000 IDs for integers).
```python
'a', 'b',
columns={'datetime': 'id'},
dtypes={'id': 'Int64'},
)
pipe.sync([
{'id': 0, 'color': 'red'},
{'id': 1, 'color': 'blue'},
{'id': 2, 'color': 'green'},
{'id': 3, 'color': 'yellow'},
])
chunks = pipe.get_data(
chunk_interval = 2,
as_iterator = True,
)
for chunk in chunks:
print(chunk)
```
- **Add server-side cursor support to …
> ⚡️ v1.6.8 Ultimate generators release!

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/config/_version.py
- meerschaum/connectors/sql/SQLConnector.py
- meerschaum/core/Pipe/_sync.py
- meerschaum/utils/misc.py
- tests/test_pipes.py
- **Allow nested chunk generators.**  
This patch more gracefully handles labels for situations with nested chunk generators and adds and explicit test for this scenario.
```python
pipe = mrsm.Pipe('foo', 'bar', instance='sql:memory')
docs = [{'color': 'red'}, {'color': 'green'}]
num_chunks = 3
num_batches = 2
def build_chunks():
return (
[
{'chunk_ix': chunk_ix, **doc}
for doc in docs
]
for chunk_ix in range(num_chunks)
)
batches = (
(
[
{'batch_ix': batch_ix, **doc}
for doc in chunk
]
for chunk in build_chunks()
)
for batch_ix in range(num_batches)
)
pipe.sync(batches)
print(pipe.get_data())
```
> ✨ v1.6.12 Allow for syncing nested generators.

- meerschaum/connectors/sql/_sql.py
Helps deal with dangerous strings better.
> json.dumps makes \u0000 too

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/config/_version.py
- meerschaum/connectors/sql/_sql.py
- **Remove `\\u0000` from strings when inserting into PostgreSQL.**  
Replace both `\0` and `\\u0000` with empty strings when streaming rows into PostgreSQL.
> 📦️ v1.6.13

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/actions/stack.py
- meerschaum/api/dash/callbacks/dashboard.py
- meerschaum/config/_version.py
- meerschaum/config/stack/__init__.py
- **Added healthchecks to `mrsm stack up`.**  
The internal Docker Compose file for `mrsm stack` was bumped to version 3.9, and secrets were replaced with environment variable references.
- **Fixed `--no-auth` when starting the API.**  
The command `mrsm start api --no-auth` now correctly handles sessions.
> 🐛 v1.6.14 Fix `--no-auth` and tweak `mrsm stack`.

- meerschaum/actions/copy.py
- meerschaum/config/_version.py
- **Sync chunks in the `copy pipes` action.**  
This will help with large out-of-memory pipes.
> ✨ v1.6.15 Add `as_iterator` to the `copy pipes` action.

- Dockerfile
- scripts/config.sh
- scripts/docker/entrypoint.sh
- scripts/portable/LINUX/mrsm
- scripts/portable/LINUX/scripts/install.sh
- scripts/portable/LINUX/scripts/uninstall.sh
- scripts/portable/MACOS/mrsm
- scripts/portable/MACOS/scripts/install.sh
- scripts/portable/MACOS/scripts/uninstall.sh
- scripts/portable/build.sh
- scripts/push.sh
Update the Docker base to Python 3.11 on Debian Bookworm and bump the portable builds to Python 3.11 as well.
> 🐋 Update `Dockerfile` and portable builds.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/_internal/arguments/_parser.py
- meerschaum/actions/api.py
- meerschaum/actions/stack.py
- meerschaum/api/routes/_misc.py
- meerschaum/config/_sync.py
- meerschaum/config/_version.py
- meerschaum/config/stack/__init__.py
- meerschaum/config/static/__init__.py
- scripts/docker/image_setup.sh
- setup.py
- **Fix `role "root" does not exist` from stack logs.**  
Although the healthcheck was working as expected, the log output was filled with `Error FATAL: role "root" does not exist`. These errors have been fixed.
- **Fix `MRSM_CONFIG` behavior when running `start api --production`.**  
Starting the Web API through `gunicorn` (i.e. `--production`) now respects `MRSM_CONFIG`. This is useful for running `stack up` with non-default credentials.
- **Added `--insecure` as an alias for `--no-auth`.**  
To compliment the newly added `--secure` flag, starting the Web API with `--insecure` will bypass authentication.
- **Bump default TimescaleDB version to PG15.**  
The default TimescaleDB version for the Meerschaum stack is now `latest-pg15-oss`.
- **Pass sysargs to `docker compose` via `stack`** …
> ⚡️ v1.7.2 Add minor improvements to the local stack.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/actions/stack.py
- meerschaum/api/dash/components.py
- meerschaum/config/__init__.py
- meerschaum/config/_edit.py
- meerschaum/config/_read_config.py
- meerschaum/config/_sync.py
- meerschaum/config/_version.py
- meerschaum/config/static/__init__.py
- meerschaum/connectors/api/_actions.py
- meerschaum/connectors/api/_login.py
- meerschaum/connectors/api/_misc.py
- meerschaum/connectors/api/_plugins.py
- meerschaum/connectors/api/_users.py
- meerschaum/connectors/parse.py
- meerschaum/connectors/sql/_users.py
- meerschaum/core/User/_User.py
- meerschaum/utils/venv/_Venv.py
- meerschaum/utils/venv/__init__.py
- scripts/setup.sh
- **Fix an issue with the local stack healthcheck.**  
Due to some edge cases, the local stack `docker-compose.yaml` file would not be correctly formatted until `edit config` had been executed. This patch ensures the files are synced with each invocation of `stack`.
- **Allow for email usernames.**  
For users who would like their usernames to match their emails, the acceptable usernames allow all alphanumeric characters as well as the following special characters: `_`, `-`, `.`, and `@`.
- **Minor bugfixes for MacOS.**  
Edge cases when mixing Brew-installed Pythons and system Pythons have been addressed.
> 🐛 v1.7.3 Bugfixes for the local stack, MacOS, and emails as usernames.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/actions/stack.py
- meerschaum/config/stack/__init__.py
- scripts/docker/image_setup.sh
- **Fix an issue when running the local stack with non-default ports.**  
Initializing a local stack with a different database port (e.g. 5433) now routes correctly within the Docker compose network (now patching to internal port to 5432).
- **Fix `upgrade mrsm` behavior.**  
Recent changes to `stack` broke the automatic `stack pull` within `mrsm upgrade mrsm`.
> 🐛 v1.7.4 Fix an issue with custom database ports.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/api/dash/callbacks/jobs.py
- meerschaum/config/_version.py
- meerschaum/connectors/sql/_pipes.py
- meerschaum/connectors/sql/_sql.py
- meerschaum/core/Pipe/_data.py
- meerschaum/core/Pipe/_fetch.py
- meerschaum/utils/daemon/Daemon.py
- meerschaum/utils/daemon/_names.py
- meerschaum/utils/dtypes/sql.py
- meerschaum/utils/formatting/_pipes.py
- meerschaum/utils/packages/_packages.py
- meerschaum/utils/sql.py
- requirements/api.txt
- requirements/full.txt
- tests/test_pipes_dtypes.py
- **Fix syncing bools within in-place SQL pipes.**  
SQL pipes may now sync bools in-place. For database flavors which lack native `BOOLEAN` support (e.g. `sqlite`, `oracle`, `mysql`), then the boolean columns must be stated in `pipe.dtypes`.
- **Fix an issue with multiple users managing jobs.**  
Extra validation was added to the web UI to allow for multiple users to interact with jobs.
- **Fix a minor formatting bug with `highlight_pipes()`.**  
Improved validation logic was added to prevent incorrectly prepending the `Pipe(` prefix.
- **Hold back `pydantic` to `<2.0.0`**  
Pydantic 2 is supported in all features except `--schedule`. Until `rocketry` supports Pydantic 2, it will be held back.
> 🐛 v2.0.1 Fix minor bugs when syncing bools in-place.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/config/_default.py
- meerschaum/config/_version.py
- meerschaum/connectors/__init__.py
- meerschaum/connectors/sql/_fetch.py
- meerschaum/connectors/sql/_pipes.py
- meerschaum/core/Pipe/__init__.py
- meerschaum/core/Pipe/_data.py
- meerschaum/core/Pipe/_deduplicate.py
- meerschaum/core/Pipe/_fetch.py
- meerschaum/core/Pipe/_sync.py
- **Syncing with `--skip-check-existing` will not apply the backtrack interval.**  
Because `--skip-check-existing` (or `check_existing=False`) is guaranteed to produce duplicates, the backtrack interval will be set to 0 when running in insert-only mode.
- **Allow for `columns` to be a list.**  
Note that building a pipe with `columns` as a list must have the datetime column named `datetime`.
```python
pipe = mrsm.Pipe('a', 'b', columns=['a'])
print(pipe.columns)
```
- **Bump default SQLAlchemy pool size to 8 connections.**
- **Fix `pipe.get_data(as_dask=True)` for JSON columns.**
> 🔧 v2.0.2 Skip backtracking when syncing with `--skip-check-existing`.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- docs/mkdocs/reference/plugins/writing-plugins.md
- meerschaum/actions/sync.py
- meerschaum/config/_version.py
- meerschaum/connectors/sql/_pipes.py
- meerschaum/connectors/sql/tables/__init__.py
- meerschaum/core/Pipe/_data.py
- meerschaum/utils/sql.py
- meerschaum/utils/typing.py
- tests/test_sync.py
- **Move `success_tuple` from arg to kwarg for `@post_sync_hook` functions.**  
To match the signature of `@pre_sync_hook` functions, `@post_sync_hook` functions now only accept `pipe` as the positional argument. The return value of the sync will now be passed as the kwarg `success_tuple`. This allows you to use the same callback function as both the pre- and post-sync hooks.
```python
from meerschaum.plugins import pre_sync_hook, post_sync_hook
@pre_sync_hook
@post_sync_hook
def log_sync(
pipe: mrsm.Pipe,
success_tuple: mrsm.SuccessTuple | None = None,
):
if success_tuple is None:
print(f"About to sync {pipe}!")
else:
success, msg = success_tuple
print(f"Finished syncing {pipe} with message:\n{msg}")
```
- **Add `sync_timestamp` and `sync_complete_timestamp` to …
> 🔧 v2.1.6 Improve sync hooks, allow index-only upserts, and bugfixes.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/_internal/shell/Shell.py
- meerschaum/actions/api.py
- meerschaum/config/_shell.py
- meerschaum/config/_version.py
- meerschaum/connectors/sql/_fetch.py
- meerschaum/connectors/sql/_pipes.py
- meerschaum/core/Pipe/_dtypes.py
- meerschaum/core/Pipe/_sync.py
- meerschaum/utils/dataframe.py
- meerschaum/utils/formatting/_pipes.py
- meerschaum/utils/misc.py
- meerschaum/utils/packages/__init__.py
- **Add `query_df()` to `meerschaum.utils.dataframe`.**  
The function `query_df()` allows you to filter dataframes by `params`, `begin`, and `end`.
```python
df = pd.DataFrame([
{'a': 1, 'color': 'red'},
{'a': 2, 'color': 'blue'},
{'a': 3, 'color': 'green'},
{'a': 4, 'color': 'yellow'},
])
from meerschaum.utils.dataframe import query_df
query_df(df, {'color': ['red', 'yellow']})
query_df(df, {'color': '_blue'}, reset_index=True)
query_df(df, {'a': 2}, select_columns=['color'])
```
- **Add `get_in_ex_params()` to `meerschaum.utils.misc`.**  
This function parses a standard `params` dictionary into tuples of include and exclude parameters.
```python
from meerschaum.utils.misc import get_in_ex_params
params = {'color': ['red', '_blue', 'green']}
in_ex_params = …
```
> ✨ v2.1.7 Add `query_df()`, improve JSON filtering and shell startup time, and more.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/_internal/entry.py
- meerschaum/config/_version.py
- meerschaum/connectors/__init__.py
- meerschaum/connectors/sql/_cli.py
- meerschaum/connectors/sql/_pipes.py
- meerschaum/utils/packages/_packages.py
- meerschaum/utils/schedule.py
- requirements/api.txt
- requirements/full.txt
- **Fix `--schedule` in the interactive shell.**  
The `--schedule` flag may now be used from both the CLI and the Shell.
- **Fix the `SQLConnector` CLI.**  
The `sql` action now correctly opens an interactive CLI.
- **Bumped `duckdb` to `>=1.0.0`.**  
The upstream breaking changes that required `duckdb` to be held back have to do with how indices behave. For now, index creation has been disabled so that `duckdb` may be upgraded to 1.0+.
> 🐛 v2.2.1 Minor bugfixes

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/__main__.py
- meerschaum/_internal/entry.py
- meerschaum/_internal/shell/Shell.py
- meerschaum/_internal/shell/updates.py
- meerschaum/actions/register.py
- meerschaum/actions/sync.py
- meerschaum/actions/upgrade.py
- meerschaum/api/routes/_pipes.py
- meerschaum/config/_formatting.py
- meerschaum/config/_paths.py
- meerschaum/config/_shell.py
- meerschaum/config/_version.py
- meerschaum/config/static/__init__.py
- meerschaum/connectors/api/_misc.py
- meerschaum/connectors/api/_request.py
- meerschaum/core/Pipe/_sync.py
- meerschaum/utils/daemon/Daemon.py
- meerschaum/utils/daemon/FileDescriptorInterceptor.py
- meerschaum/utils/daemon/RotatingFile.py
- meerschaum/utils/daemon/__init__.py
- meerschaum/utils/formatting/__init__.py
- meerschaum/utils/formatting/_jobs.py
- meerschaum/utils/misc.py
- meerschaum/utils/packages/__init__.py
- meerschaum/utils/prompt.py
- meerschaum/utils/schedule.py
- **Fix daemon stability.**  
Broken file handlers are now better handled, and this should keep background jobs from crashing.
- **Improve `show jobs` output.**  
The `show jobs` table now includes the `SuccessTuple` of the most recent run (when jobs are stopped).
- **Use a plugin's `__doc__` string as the default description.**  
When registering a new plugin, the `__doc__` string will be used as the default value for the description.
- **Pipes without connectors are no longer considered errors when syncing.**  
When a pipe has an ordinary string in place of a connector (e.g. externally managed), return early and consider success rather than throwing an error.
```python
pipe = mrsm.Pipe('a', 'b')
pipe.sync()
```
- **Add update announcements.**  
When new …
> 🐛 v2.2.7 Fix log file descriptors, improve `show jobs`, add announcements.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/_internal/arguments/_parser.py
- meerschaum/actions/show.py
- meerschaum/config/_version.py
- meerschaum/connectors/sql/_pipes.py
- meerschaum/core/Pipe/_data.py
- meerschaum/utils/dataframe.py
- meerschaum/utils/formatting/_pipes.py
- meerschaum/utils/misc.py
- requirements/api.txt
- requirements/full.txt
- **Add relative formats to `--begin` and `--end`.**  
The flags `--begin` and `--end` support values in the format `[N] [unit] ago`:
```bash
mrsm sync pipes --begin '3 days ago'
```
Add a second delta format (recommended to be denoted by the keyword `rounded`) to round the timestamp to a clean value:
```bash
mrsm clear pipes --end '1 month ago rounded 1 day'
```
Supported units are `seconds`, `minutes`, `hours`, `days`, `weeks`, `months` (`ago` only), and `years`.
- **Respect `--begin`, `--end`, and `--params` in `show rowcounts`.**  
The flags `--begin`, `--end`, and `--params` are now handled in the action `show rowcounts`.
> ✨ v2.4.9 Add relative dates to `--begin`, `--end`.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/api/routes/_pipes.py
- meerschaum/config/_version.py
- meerschaum/connectors/api/_pipes.py
- meerschaum/connectors/sql/_fetch.py
- meerschaum/connectors/sql/_pipes.py
- meerschaum/connectors/valkey/_pipes.py
- meerschaum/core/Pipe/__init__.py
- meerschaum/core/Pipe/_attributes.py
- meerschaum/core/Pipe/_dtypes.py
- meerschaum/core/Pipe/_sync.py
- meerschaum/utils/dataframe.py
- meerschaum/utils/dtypes/sql.py
- meerschaum/utils/sql.py
- tests/test_pipes_dtypes.py
- tests/test_sync.py
- tests/utils/test_sql.py
- **Add `Pipe.tzinfo`.**  
Check if a pipe is timezone-aware with `tzinfo`:
```python
'demo', 'timezone', 'aware',
columns={'datetime': 'dt'},
)
print(pipe.tzinfo)
'demo', 'timezone', 'naive',
columns={'datetime': 'dt'},
dtypes={'dt': 'datetime64[ns]'},
)
print(pipe.tzinfo)
```
- **Improve timezone enforcement when syncing.**
- **Fix timezone-aware datetime truncation for MSSQL**
> 🐛 v2.6.1 Improve timezone-aware enforcement, add `Pipe.tzinfo`.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/_internal/docs/index.py
- meerschaum/config/_version.py
- meerschaum/connectors/sql/_SQLConnector.py
- meerschaum/connectors/sql/_pipes.py
- meerschaum/connectors/valkey/_pipes.py
- meerschaum/core/Pipe/_attributes.py
- meerschaum/core/Pipe/_drop.py
- meerschaum/utils/dataframe.py
- meerschaum/utils/dtypes/__init__.py
- meerschaum/utils/packages/__init__.py
- meerschaum/utils/packages/_packages.py
- meerschaum/utils/sql.py
- scripts/test.sh
- tests/connectors.py
- tests/pipes.py
- tests/test_deduplicate.py
- tests/test_pipe_data.py
- tests/test_pipes_dtypes.py
- tests/test_sync.py
- tests/test_users.py
- tests/test_verify.py
- **Improve metadata performance when syncing.**  
Syncs via the SQLConnector now cache schema and index metadata, speeding up transactions.
- **Fix upserts for MySQL / MariaDB.**  
Upserts in MySQL and MariaDB now use `ON DUPLICATE` instead of `REPLACE INTO`.
- **Fix dtype detection for index columns.**  
A bug where new index columns were incorrectly created as `INT` has been fixed.
- **Delete old keys when dropping Valkey pipes.**  
Dropping a pipe from Valkey now clears all old index keys.
> v2.6.6 Fix dtypes for new indices, update tests.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/config/_version.py
- meerschaum/core/Pipe/_dtypes.py
- meerschaum/core/Pipe/_sync.py
- meerschaum/utils/dataframe.py
- meerschaum/utils/dtypes/__init__.py
- tests/test_jobs.py
- **Improve datetime timezone-awareness enforcement performance.**  
Datetime columns are only parsed for timezone awareness if the desired awareness differs. This drastically speeds up sync times.
- **Switch to `tz_localize()` when stripping timezone information.**  
The previous method of using a lambda to replace individual `tzinfo` attributes did not scale well. Using `tz_localize()` can be vectorized and greatly speeds up syncs, especially with large chunks.
- **Add `enforce_dtypes` to `Pipe.filter_existing()`.**  
You may optionally enforce dtype information during `filter_existing()`. This may be useful when implementing custom syncs for instance connectors. Note this may impact memory and compute performance.
```python
pipe = …
```
> ⚡️ v2.6.10 Speed up dtype enforcement, fix Oracle auto-incrementing IDs.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/api/routes/_actions.py
- meerschaum/api/routes/_jobs.py
- meerschaum/config/_version.py
- meerschaum/connectors/api/_pipes.py
- meerschaum/core/User/__init__.py
- setup.py
- tests/test_jobs.py
- **Enforce security settings for creating jobs.**  
Jobs and remote actions will only be accessible to admin users when running with `--secure` (`system:permissions:actions:non_admin` in config).
> 🔒️ v2.6.12 Enforce permissions security settings for jobs and remote actions.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- docs/mkdocs/reference/connectors/instance-connectors.md
- meerschaum/actions/bootstrap.py
- meerschaum/actions/copy.py
- meerschaum/config/_default.py
- meerschaum/config/_version.py
- meerschaum/connectors/sql/_fetch.py
- meerschaum/connectors/sql/_pipes.py
- meerschaum/core/Pipe/_attributes.py
- meerschaum/core/Pipe/_bootstrap.py
- meerschaum/core/Pipe/_sync.py
- meerschaum/utils/prompt.py
- tests/test_sync.py
- **Fix inplace syncs without a `datetime` axis.**  
A bug introduced by a performance optimization has been fixed. Inplace pipes without a `datetime` axis will skip searching for date bounds. Setting `upsert` to `true` will bypass this bug for previous releases.
- **Skip invoking `get_sync_time()` for pipes without a `datetime` axis.**  
Invoking an instance connector's `get_sync_time()` method will now only occur when `datetime` is set.
- **Remove `guess_datetime()` check from `SQLConnector.get_sync_time()`.**  
Because sync times are only checked for pipes with a dedicated `datetime` column, the `guess_datetime()` check has been removed from the `SQLConnector.get_sync_time()` method.
- **Skip persisting default `target` to parameters.**  
The default target table name will no longer be …
> 🐛 v2.6.15 Fix inplace syncs without a datetime column.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/_internal/arguments/_parse_arguments.py
- meerschaum/_internal/arguments/_parser.py
- meerschaum/actions/clear.py
- meerschaum/actions/edit.py
- meerschaum/actions/verify.py
- meerschaum/config/_version.py
- meerschaum/connectors/sql/_fetch.py
- meerschaum/connectors/sql/_instance.py
- meerschaum/connectors/sql/_pipes.py
- meerschaum/core/Pipe/_attributes.py
- meerschaum/core/Pipe/_dtypes.py
- meerschaum/core/Pipe/_fetch.py
- meerschaum/core/Pipe/_sync.py
- meerschaum/core/Pipe/_verify.py
- meerschaum/jobs/__init__.py
- meerschaum/utils/dataframe.py
- meerschaum/utils/dtypes/sql.py
- meerschaum/utils/formatting/__init__.py
- meerschaum/utils/formatting/_pipes.py
- meerschaum/utils/sql.py
- meerschaum/utils/venv/__init__.py
- tests/test_pipes_dtypes.py
- **Allow for dynamic targets in SQL queries.**  
Include a pipe definition in double curly braces (à la Jinja) to substitute a pipe's target into a templated query.
```python
pipe = mrsm.Pipe('demo', 'template', target='foo', instance='sql:local')
_ = pipe.register()
downstream_pipe = mrsm.Pipe(
'sql:local', 'template',
instance='sql:local',
parameters={
'sql': "SELECT *\nFROM {{Pipe('demo', 'template', instance='sql:local')}}"
},
)
conn = mrsm.get_connector('sql:local')
print(conn.get_pipe_metadef(downstream_pipe))
```
- **Add `--skip-enforce-dtypes`.**  
To override a pipe's `enforce` parameter, pass `--skip-enforce-dtypes` to a sync.
- **Skip enforcing custom dtypes when `enforce=False`.**  
To avoid confusion, special Meerschaum data types (`numeric`, …
> Enforce `DATETIMEOFFSET` as UTC.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/actions/sql.py
- meerschaum/config/_default.py
- meerschaum/config/_version.py
- meerschaum/connectors/sql/_cli.py
- meerschaum/connectors/sql/_create_engine.py
- meerschaum/connectors/sql/_pipes.py
- meerschaum/connectors/sql/_sql.py
- meerschaum/utils/daemon/Daemon.py
- meerschaum/utils/packages/__init__.py
- meerschaum/utils/venv/_Venv.py
- meerschaum/utils/venv/__init__.py
- tests/test_jobs.py
- tests/test_pipes_dtypes.py
- **Add bulk inserts for MSSQL.**  
To disable this behavior, set `system:connectors:sql:bulk_insert:mssql` to `false`. Bulk inserts for PostgreSQL-like flavors may now be disabled as well.
> ⚡️ v2.7.5 Add bulk insert for MSSQL, fix venv deactivation race conditions.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/_internal/shell/Shell.py
- meerschaum/_internal/shell/ShellCompleter.py
- meerschaum/actions/clear.py
- meerschaum/actions/copy.py
- meerschaum/actions/sync.py
- meerschaum/api/dash/pipes.py
- meerschaum/config/_default.py
- meerschaum/config/_version.py
- meerschaum/connectors/api/_misc.py
- meerschaum/connectors/api/_pipes.py
- meerschaum/connectors/sql/_SQLConnector.py
- meerschaum/connectors/sql/_pipes.py
- meerschaum/connectors/sql/_sql.py
- meerschaum/jobs/_Job.py
- meerschaum/plugins/__init__.py
- meerschaum/utils/daemon/Daemon.py
- meerschaum/utils/daemon/__init__.py
- meerschaum/utils/misc.py
- meerschaum/utils/packages/__init__.py
- meerschaum/utils/packages/_packages.py
- meerschaum/utils/prompt.py
- meerschaum/utils/venv/__init__.py
- tests/test_jobs.py
- tests/test_pipes_dtypes.py
- **Make temporary table names configurable.**  
The values for temporary SQL tables may be set in `MRSM{system:connectors:sql:instance:temporary_target}`. The new default prefix is `'_'`, and the new default transaction length is 4. The values have been re-ordered to target, transaction ID, then label.
- **Add connector completions to `copy pipes`.**  
When copying pipes, the connector keys prompt will offer auto-complete suggestions.
- **Fix stale job results.**  
When polling for job results, the job result is dropped from in-memory cache to avoid overwriting the on-disk result.
- **Format row counts and seconds into human-friendly text.**  
Row counts and sync durations are now formatted into human-friendly representations.
- **Add digits to `generate_password()`.**  
Random strings …
> 🔧 v2.7.6 Make temporary table names configurable.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/api/__init__.py
- meerschaum/api/routes/_pipes.py
- meerschaum/config/_default.py
- meerschaum/config/_version.py
- meerschaum/config/static/__init__.py
- meerschaum/connectors/sql/_cli.py
- meerschaum/connectors/sql/_create_engine.py
- meerschaum/connectors/sql/_users.py
- meerschaum/core/Pipe/_verify.py
- meerschaum/utils/dataframe.py
- scripts/docker/image_setup.sh
- **Increase username limit to 60 characters.**
- **Add chunk retries to `Pipe.verify()`.**
- **Add instance keys to remaining pipes endpoints.**
- **Misc bugfixes.**
> 🧹 v2.8.3 Clean up API endpoints.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- docs/mkdocs/reference/api-instance/nginx.md
- docs/mkdocs/reference/connectors/instance-connectors.md
- meerschaum/_internal/arguments/_parser.py
- meerschaum/actions/drop.py
- meerschaum/actions/start.py
- meerschaum/actions/sync.py
- meerschaum/api/__init__.py
- meerschaum/api/routes/_pipes.py
- meerschaum/config/_version.py
- meerschaum/connectors/sql/_SQLConnector.py
- meerschaum/core/Pipe/_verify.py
- meerschaum/jobs/systemd.py
- meerschaum/utils/packages/_packages.py
- meerschaum/utils/process.py
- meerschaum/utils/schedule.py
- meerschaum/utils/sql.py
- meerschaum/utils/venv/__init__.py
- **Allow for pattern matching in `allowed_instance_keys`.**  
You may now generalize the instances exposed by the API by using Unix-style patterns in the list `system:api:permissions:instances:allowed_instance_keys`:
```json
{
"api": {
"permissions": {
"instances": {
"allowed_instance_keys": [
"valkey:*",
"*_dev"
]
}
}
}
}
```
- **Return pipe attributes for the route `/pipes/{connector}/{metric}/{location}`.**  
The API routes `/pipes/{connector}/{metric}/{location}` and `/pipes/{connector}/{metric}/{location}/attributes` both return pipe attributes.
- **Check entire batches for `verify rowcounts`.**  
The command `verify rowcounts` will now check batch boundaries before checking row-counts for individual chunks. This should moderately increase performance.
- **Kill orphaned child …
> 🔐 v2.8.4 Improve API allowed instance keys settings.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/_internal/shell/Shell.py
- meerschaum/api/dash/pages/pipes.py
- meerschaum/api/resources/templates/termpage.html
- meerschaum/config/_version.py
- meerschaum/core/Pipe/_data.py
- meerschaum/core/Pipe/_verify.py
- meerschaum/utils/dtypes/__init__.py
- meerschaum/utils/misc.py
- meerschaum/utils/sql.py
- tests/test_sync.py
- **Fix in-place syncs with `GEOMETRY` columns.**
The query to retrieve `GEOMETRY` data types for PostGIS has been fixed.
- **Consolidate 1-minute chunks in `Pipe.get_chunk_bounds()`.**  
The chunk bounds returned from `Pipe.get_chunk_bounds()` (without specifiying an `end`) now consolidate the 1-minute chunk into the last chunk:
```python
pipe = mrsm.Pipe('demo', 'chunk_bounds', columns={'datetime': 'dt'}, instance='sql:local')
pipe.sync([
{'dt': '2025-01-01'},
{'dt': '2025-01-02'},
])
mrsm.pprint(pipe.get_chunk_bounds(bounded=True))
```
- **Remove unnecessary `CREATE SCHEMA IF EXISTS` checks.**
- **Fix unsupported syntax for Python 3.8.**
- **Truncate long connector keys in the Shell prompt.**
- **Fix null location keys behavior for pipes cards.**
> 🐛 v2.9.2 Fix in-place PostGIS syncs, improve chunk bounds for verifications

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/api/dash/callbacks/dashboard.py
- meerschaum/api/dash/pipes.py
- meerschaum/api/resources/static/css/dash.css
- meerschaum/config/_version.py
- meerschaum/connectors/sql/_sql.py
- meerschaum/utils/dataframe.py
- meerschaum/utils/dtypes/__init__.py
- meerschaum/utils/sql.py
- tests/test_sync.py
- **Add the `Query Data` dropdown to pipes' cards.**  
Similar to the `Recent Data` dropdown, you can now explore a pipe's data with the `Query Data` dropdown. This supports `begin`, `end`, `params`, and `limit` filtering.
- **Additional fixes for in-place syncs on PostGIS.**  
Geometry columns are now correctly coalesced for PostGIS.
> ✨ v2.9.5 Add the "Query Data" dropdown to the pipe cards.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/api/dash/callbacks/dashboard.py
- meerschaum/api/dash/callbacks/pipes.py
- meerschaum/api/dash/components.py
- meerschaum/api/dash/pipes.py
- meerschaum/api/resources/static/css/dash.css
- meerschaum/config/_default.py
- meerschaum/config/_version.py
- meerschaum/core/Pipe/_cache.py
- meerschaum/utils/pipes.py
- **Fix pipe page routing.**  
Links to specific pipes in the dashboard are now routed correctly.
- **Fix cache invalidation for pipes using Valkey connectors.**  
Pipes using a `valkey` connector to store cache (rather than on-disk) will now correctly invalidate cache on demand.
> 🐛 v3.0.3 Fix cache invalidation for `valkey` connectors.

- CHANGELOG.md
- docs/mkdocs/news/changelog.md
- meerschaum/api/dash/pipes.py
- meerschaum/config/_default.py
- meerschaum/config/_version.py
- meerschaum/connectors/sql/_pipes.py
- meerschaum/core/Pipe/_cache.py
- meerschaum/utils/dataframe.py
- meerschaum/utils/packages/__init__.py
- meerschaum/utils/venv/__init__.py
- scripts/test.sh
- tests/test_sync.py
- **Fix pipe page routing.**  
Links to specific pipes in the dashboard are now routed correctly.
- **Fix cache invalidation for pipes using Valkey connectors.**  
Pipes using a `valkey` connector to store cache (rather than on-disk) will now correctly invalidate cache on demand.
- **Fix Python 3.9 compatability.**  
An issue breaking Python 3.9 has been fixed.
- **Prevent resolving symlinks for pipe's parameters card.**  
The pipe card in dash will no longer resolve symlinks.
- **Handle `pd.NA` values in JSON columns for `filter_unseen_df()`.**  
Non-string values (e.g. `pd.NA`) are now correctly handled for JSON columns in `filter_unseen_df()`. 
- **Disable `uv` when running inside a virtual environment.**
> 🐛 v3.0.4 Fix Python 3.9 compatability.
